name: NaturalInteraction
version: 1.3.0
main: id.naturalsmp.naturalinteraction.NaturalInteraction
api-version: 1.21
authors: [NaturalSMP]
description: Advanced RPG Story and NPC Interaction System
depend: [Citizens, NaturalCore, ProtocolLib]
softdepend: [PlaceholderAPI, NaturalDungeon, NaturalPass, ItemsAdder]

commands:
  interaction:
    description: Main command for interactions
    usage: /interaction <subcommand>
    aliases: [inter, ni]
  story:
    description: View your story progress
    usage: /story
  sidequest:
    description: View your active sidequests
    usage: /sidequest
