name: NaturalInteraction
version: 1.0.0
main: id.naturalsmp.naturalinteraction.NaturalInteraction
api-version: 1.21
authors: [NaturalSMP]
description: Advanced RPG Story and NPC Interaction System
depend: [Citizens, NaturalCore]
softdepend: [ProtocolLib, NaturalPass]

commands:
  interaction:
    description: Main command for interactions
    usage: /interaction <subcommand>
    aliases: [inter, ni]
